### ISSUE TITLE
Support for ST4?

### ISSUE THREAD

**Issue by Unknow0059** [oleg-shilo/sublime-codemap#42]
Does this support ST4?

I tried it but it does not seem to be working.

**Comment by oleg-shilo** [comment]
Seems to work for me. Can you share the doc file that does not work and I can have a look at it.

**Comment by Unknow0059** [comment]
Hours ago I had tried reinstalling a few times to see if it would start working, then kept it uninstalled since, I tested on lua and python files.
Now I tried again, this time it's also a python file.

I installed it, Toggled it, saw no effect, opened the console and saw the following error:

```
Package Control: Installed package "CodeMap" 1.0.14
ignored packages updated to: ["SideBarEnhancements", "SideBarHider", "Theme - Monokai Pro", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading python 3.3 plugin CodeMap.code_map
reloading python 3.3 plugin CodeMap.code_map_support
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
Package Control: resuming indexer
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 1499, in run_
    return self.run(edit)
  File "E:\Save Data\Windows Setting Up\ST3 Data\Installed Packages\CodeMap.sublime-package\code_map.py", line 853, in run
  File "E:\Portable\SublimeText\Lib\python33\sublime.py", line 1087, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 859, in on_load
    run_view_callbacks('on_load', view_id)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "E:\Save Data\Windows Setting Up\ST3 Data\Installed Packages\CodeMap.sublime-package\code_map.py", line 885, in on_load
    refresh_map_for(view)
  File "E:\Save Data\Windows Setting Up\ST3 Data\Installed Packages\CodeMap.sublime-package\code_map.py", line 290, in refresh_map_for
    generate_from(file)
  File "E:\Save Data\Windows Setting Up\ST3 Data\Installed Packages\CodeMap.sublime-package\code_map.py", line 268, in generate_from
    map_view.run_command('code_map_generator', {"source": file})
  File "E:\Portable\SublimeText\Lib\python33\sublime.py", line 1395, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 1495, in run_
    self.view.end_edit(edit)
  File "E:\Portable\SublimeText\Lib\python33\sublime.py", line 1356, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 924, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "E:\Portable\SublimeText\Lib\python33\sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "E:\Save Data\Windows Setting Up\ST3 Data\Installed Packages\BracketFlasher.sublime-package\bracket_flasher.py", line 26, in on_modified
    start_location = view.sel()[0].begin() - 1
  File "E:\Portable\SublimeText\Lib\python33\sublime.py", line 1087, in __getitem__
    raise IndexError()
IndexError
```

Then I switched tabs, and the CodeMap buffer that was open was updated with visible contents.

In a previous attempt I'd seen an error and assumed it caused CodeMap not to work, but in hindsight, it could've been non-critical (like this one...?).

**Comment by Unknow0059** [comment]
I'll be closing this. The other, conflicting plugin wasn't maintained even a single time, and it never worked in the first place.
